begin;

create table if not exists public.tournament_data_history (
  id bigint generated by default as identity primary key,
  tournament_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  tournament_name text,
  tournament_type text,
  revision bigint,
  data jsonb not null,
  captured_at timestamptz not null default now()
);

create index if not exists tournament_data_history_tournament_captured_idx
  on public.tournament_data_history (tournament_id, captured_at desc);

create index if not exists tournament_data_history_user_captured_idx
  on public.tournament_data_history (user_id, captured_at desc);

alter table public.tournament_data_history enable row level security;

drop policy if exists "Owners can read tournament history" on public.tournament_data_history;
create policy "Owners can read tournament history"
  on public.tournament_data_history
  for select
  using (auth.uid() = user_id);

revoke all on table public.tournament_data_history from anon;
grant select on table public.tournament_data_history to authenticated;

create or replace function public.count_completed_tournament_games(payload jsonb)
returns integer
language sql
immutable
set search_path = pg_catalog, public
as $$
  select
    coalesce((
      select count(*)::integer
      from jsonb_array_elements(coalesce(payload->'schedule', '[]'::jsonb)) as rounds(round_data)
      cross join lateral jsonb_array_elements(
        case when jsonb_typeof(round_data) = 'array' then round_data else '[]'::jsonb end
      ) as games(game_data)
      where nullif(game_data->>'s1', '') is not null
        and nullif(game_data->>'s2', '') is not null
    ), 0)
    + coalesce((
      select count(*)::integer
      from jsonb_array_elements(coalesce(payload->'brackets', '[]'::jsonb)) as games(game_data)
      where nullif(game_data->>'s1', '') is not null
        and nullif(game_data->>'s2', '') is not null
    ), 0);
$$;

revoke all on function public.count_completed_tournament_games(jsonb) from public;

create or replace function public.archive_tournament_data_before_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  completed_scores_decreased boolean;
  periodic_snapshot_due boolean;
begin
  if old.data is distinct from new.data then
    completed_scores_decreased := public.count_completed_tournament_games(old.data)
      > public.count_completed_tournament_games(new.data);
    periodic_snapshot_due := not exists (
      select 1
      from public.tournament_data_history history
      where history.tournament_id = old.id
        and history.captured_at >= now() - interval '15 minutes'
    );

    if completed_scores_decreased or periodic_snapshot_due then
      insert into public.tournament_data_history (
        tournament_id, user_id, tournament_name, tournament_type, revision, data, captured_at
      ) values (
        old.id, old.user_id, old.name, old.type, old.revision, old.data, now()
      );
    end if;

    if periodic_snapshot_due then
      delete from public.tournament_data_history
      where tournament_id = old.id
        and captured_at < now() - interval '90 days';
    end if;
  end if;
  return new;
end;
$$;

revoke all on function public.archive_tournament_data_before_change() from public;

drop trigger if exists tournaments_archive_data_before_change on public.tournaments;
create trigger tournaments_archive_data_before_change
before update of data on public.tournaments
for each row
execute function public.archive_tournament_data_before_change();

comment on table public.tournament_data_history is
  'Cópias imutáveis dos dados do torneio antes de cada alteração, para recuperação de placares, rodadas e chaves.';

commit;
